### ISSUE TITLE
Some error msg while installaing

### ISSUE THREAD

**Issue by aburousan** [tanner-trickle/EXCEED-DM#6]
While installation i have seen this errors..
Is there something wrong?
```
/home/rousan/Coding/Fortran/Darkmatter/EXCEED-DM/EXCEED-DMv1.1.0/src/external/special_functions.f90:21388:16:

21386 |       do k = 1, 100
      |                   2
21387 |          r = 0.5D+00 * r * x * x / ( k * ( 2.0D+00 * k + 1.0D+00 ) )
21388 |          r1 = h(k+1) * r
      |                1
Warning: Array reference at (1) out of bounds (101 > 100) in loop beginning at (2)
/home/rousan/Coding/Fortran/Darkmatter/EXCEED-DM/EXCEED-DMv1.1.0/src/external/special_functions.f90:21412:16:

21410 |       do k = 1, 100
      |                   2
21411 |          r = 0.5D+00 * r * x * x / ( k * ( 2.0D+00 * k + 1.0D+00 ) )
21412 |          r1 = d(k+1) * r
      |                1
Warning: Array reference at (1) out of bounds (101 > 100) in loop beginning at (2)
/home/rousan/Coding/Fortran/Darkmatter/EXCEED-DM/EXCEED-DMv1.1.0/src/external/special_functions.f90:21424:16:

21422 |       do k = 1, 100
      |                   2
21423 |          r = 0.5D+00 * r * x * x / ( k * ( 2.0D+00 * k - 1.0D+00 ) )
21424 |          r1 = d(k+1) * r
      |                1
Warning: Array reference at (1) out of bounds (101 > 100) in loop beginning at (2)
```

**Comment by tanner-trickle** [comment]
Hey @aburousan these warnings are coming from the subroutines in an external library, special_functions.f90 (https://people.sc.fsu.edu/~jburkardt/f_src/special_functions/special_functions.html). Fortran does not have built in support for many special functions, e.g., Legendre polynomials used for spherical harmonics, and this is the library EXCEED-DM currently uses to compute those functions. 

This library contains many functions which are not used by EXCEED-DM, and these warnings seem to be coming from one of those functions. For now, I've opted to leave the external source code unchanged, and simply ignore this warning during compilation, since it should not affect EXCEED-DM.

**Comment by aburousan** [comment]
Thank you
